version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - /c/Users/Hashmi/Desktop/ADBInterview/adb_test/tmp:/tmp
      - /c/Users/Hashmi/Desktop/ADBInterview/adb_test/src:/src
    

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - /c/Users/Hashmi/Desktop/ADBInterview/adb_test/src:/src

  mongo:
    build: .
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /c/Users/Hashmi/Desktop/ADBInterview/adb_test/db/:/data/db
    command: /usr/bin/mongod --bind_ip 0.0.0.0

    